/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TriggerWarning } from "./TriggerWarning";
import { TriggerWarningCountArgs } from "./TriggerWarningCountArgs";
import { TriggerWarningFindManyArgs } from "./TriggerWarningFindManyArgs";
import { TriggerWarningFindUniqueArgs } from "./TriggerWarningFindUniqueArgs";
import { DeleteTriggerWarningArgs } from "./DeleteTriggerWarningArgs";
import { TriggerWarningService } from "../triggerWarning.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => TriggerWarning)
export class TriggerWarningResolverBase {
  constructor(
    protected readonly service: TriggerWarningService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "TriggerWarning",
    action: "read",
    possession: "any",
  })
  async _triggerWarningsMeta(
    @graphql.Args() args: TriggerWarningCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [TriggerWarning])
  @nestAccessControl.UseRoles({
    resource: "TriggerWarning",
    action: "read",
    possession: "any",
  })
  async triggerWarnings(
    @graphql.Args() args: TriggerWarningFindManyArgs
  ): Promise<TriggerWarning[]> {
    return this.service.triggerWarnings(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => TriggerWarning, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "TriggerWarning",
    action: "read",
    possession: "own",
  })
  async triggerWarning(
    @graphql.Args() args: TriggerWarningFindUniqueArgs
  ): Promise<TriggerWarning | null> {
    const result = await this.service.triggerWarning(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => TriggerWarning)
  @nestAccessControl.UseRoles({
    resource: "TriggerWarning",
    action: "delete",
    possession: "any",
  })
  async deleteTriggerWarning(
    @graphql.Args() args: DeleteTriggerWarningArgs
  ): Promise<TriggerWarning | null> {
    try {
      return await this.service.deleteTriggerWarning(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
