/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ReadingStatus } from "./ReadingStatus";
import { ReadingStatusCountArgs } from "./ReadingStatusCountArgs";
import { ReadingStatusFindManyArgs } from "./ReadingStatusFindManyArgs";
import { ReadingStatusFindUniqueArgs } from "./ReadingStatusFindUniqueArgs";
import { DeleteReadingStatusArgs } from "./DeleteReadingStatusArgs";
import { ReadingStatusService } from "../readingStatus.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ReadingStatus)
export class ReadingStatusResolverBase {
  constructor(
    protected readonly service: ReadingStatusService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ReadingStatus",
    action: "read",
    possession: "any",
  })
  async _readingStatusesMeta(
    @graphql.Args() args: ReadingStatusCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ReadingStatus])
  @nestAccessControl.UseRoles({
    resource: "ReadingStatus",
    action: "read",
    possession: "any",
  })
  async readingStatuses(
    @graphql.Args() args: ReadingStatusFindManyArgs
  ): Promise<ReadingStatus[]> {
    return this.service.readingStatuses(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ReadingStatus, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ReadingStatus",
    action: "read",
    possession: "own",
  })
  async readingStatus(
    @graphql.Args() args: ReadingStatusFindUniqueArgs
  ): Promise<ReadingStatus | null> {
    const result = await this.service.readingStatus(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ReadingStatus)
  @nestAccessControl.UseRoles({
    resource: "ReadingStatus",
    action: "delete",
    possession: "any",
  })
  async deleteReadingStatus(
    @graphql.Args() args: DeleteReadingStatusArgs
  ): Promise<ReadingStatus | null> {
    try {
      return await this.service.deleteReadingStatus(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
