/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Serial } from "./Serial";
import { SerialCountArgs } from "./SerialCountArgs";
import { SerialFindManyArgs } from "./SerialFindManyArgs";
import { SerialFindUniqueArgs } from "./SerialFindUniqueArgs";
import { DeleteSerialArgs } from "./DeleteSerialArgs";
import { SerialService } from "../serial.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Serial)
export class SerialResolverBase {
  constructor(
    protected readonly service: SerialService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Serial",
    action: "read",
    possession: "any",
  })
  async _serialsMeta(
    @graphql.Args() args: SerialCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Serial])
  @nestAccessControl.UseRoles({
    resource: "Serial",
    action: "read",
    possession: "any",
  })
  async serials(@graphql.Args() args: SerialFindManyArgs): Promise<Serial[]> {
    return this.service.serials(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Serial, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Serial",
    action: "read",
    possession: "own",
  })
  async serial(
    @graphql.Args() args: SerialFindUniqueArgs
  ): Promise<Serial | null> {
    const result = await this.service.serial(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Serial)
  @nestAccessControl.UseRoles({
    resource: "Serial",
    action: "delete",
    possession: "any",
  })
  async deleteSerial(
    @graphql.Args() args: DeleteSerialArgs
  ): Promise<Serial | null> {
    try {
      return await this.service.deleteSerial(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
